apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-24
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ncs-nginx
  template:
    metadata:
      labels:
        app: ncs-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
